name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Generate Snake
        uses: ridedott/create-snake@v0.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          file_type: 'svg'
          output_directory: './dist'

      - name: Set output
        env:
          GIF_FILE: dist/github-contribution-grid-snake.gif
          SVG_FILE: dist/github-contribution-grid-snake.svg
        run: |
          echo "::set-env name=GIF_FILE::$GIF_FILE"
          echo "::set-env name=SVG_FILE::$SVG_FILE"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          GIF_FILE: ${{ env.GIF_FILE }}
          SVG_FILE: ${{ env.SVG_FILE }}
